- name: Download and Extract Mysql Sql Cluster binaries
  unarchive:
    src: "http://dev.mysql.com/get/Downloads/MySQL-Cluster-7.3/mysql-cluster-gpl-7.3.4-linux-glibc2.5-x86_64.tar.gz"
    dest: /var/tmp
    remote_src: yes
  become: true

- name: Extract binaries
  command: tar -C /usr/local -xzf /var/tmp/mysql-cluster-gpl-7.3.4-linux-glibc2.5-x86_64.tar.gz
  args:
    creates: /usr/local/mysql-cluster-gpl-7.6.9-linux-glibc2.5-x86_64
  become: true

#- name: Link binary directory to short name
#  command: ln -s /usr/local/mysql-cluster-gpl-7.6.9-linux-glibc2.5-x86_64 /usr/local/mysql
- name: Create /usr/local/mysql directory
  file:
    path: /usr/local/mysql
    state: directory
  become: true

- name: Create symlink for /usr/local/mysql
  file:
    src: /usr/local/mysql-cluster-gpl-7.6.9-linux-glibc2.5-x86_64
    dest: /usr/local/mysql
    state: link
  become: true
