- name: Install dependencies
  apt: pkg=libaio1
  when: ansible_distribution == "Debian"
  become: true

- name: Download binaries
  command: wget --continue -P "{{ var_dir }}" "{{ mysql_dl_url }}"
  become: true

- name: Extract binaries
  command: tar -C /usr/local -xzf {{ var_dir }}/{{ mysql_dl_tar }} creates="{{ mysql_dl_tar_dir }}"
  become: true

- name: "Create mysql ndbd required dir"
  file:
   path: "{{ mysql_dl_tar_dir }}"
   state: directory
   mode: 0644
  become: true

- name: Link binary directory to short name
  command: ln -s /usr/local/"{{ mysql_dl_tar_dir }}" /usr/local/mysql creates=/usr/local/mysql
  become: true

- name: Create mysql group
  group:
    name: mysql
    system: yes
  become: true

- name: Create myslq user
  user:
    name: mysql
    system: yes
    createhome: no
    group: mysql
  become: true

#- name: Set permissions
#  shell: chown -R mysql /usr/local/mysql/data && chgrp -R mysql /usr/local/mysql/
#  become: true

- name: "Create mysql ndbd required dir"
  file:
   path: "{{item}}"
   state: directory
   mode: 0644
  with_items:
  - "/usr/local/mysql"
  - "/usr/local/mysql/data"
  - "/usr/local/mysql/data/mysql"
  become: true

- name: "Create /usr/local/mysql/data/mysql/user.frm"
  file:
   path: "/usr/local/mysql/data/mysql/user.frm"
   state: touch
   mode: 0644
  become: true

- name: Install mysql DB
  command: ./mysql_install_db --user=root --base-dir=
  args:
    chdir: "{{ mysql_dl_tar_dir }}/scripts/"
  become: true

- name: Install init file
  command: install /usr/local/mysql/support-files/mysql.server /etc/init.d/
  args:
    creates: /etc/init.d/mysql.server
  become: true

- name: Install config
  template:
    src: my.cnf
    dest: /etc/my.cnf
  become: true

- name: Activate init script and start mysql server
  service:
    name: mysql.server
    enabled: yes
    state: started
  become: true
