---
- name: Check NDB Cluster
  command: ndb_mgmd
  become: true
  register: ndb_check

- debug: msg="{{ ndb_check.stdout }}"
- debug: msg=" mysql root password is {{ ndb_check.stdout }}"
- debug: msg=" run ndb_mgmd on the management node to test connections"
