- hosts: mysql_cluster_mgm
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - import_tasks: "mysql-cluster-mgm.yml"

- hosts: mysql_cluster_data
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - import_tasks: "mysql-cluster-data.yml"

- hosts: mysql_cluster_sql
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - import_tasks: "mysql-cluster-sql.yml"
  - import_tasks: "secure_installation.yml"
  - import_tasks: "configure.yml"

- hosts: mysql_cluster_mgm
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - import_tasks: "instructions.yml"
