- hosts: mysql_cluster_mgm
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - import_tasks: "mysql-cluster-mgm.yml"

- hosts: mysql_cluster_data
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - import_tasks: "mysql-cluster-data.yml"

- hosts: mysql_cluster_sql
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - import_tasks: "mysql-cluster-sql.yml"

#- hosts: mysql_cluster_mgm
#  become: yes
#  become_user: root
#  become_method: sudo
#  tasks:
#  - import_tasks: "instructions.yml"
