- name: Add Mysql Repo
  template:
    src: mysql-community-7.repo
    dest: /etc/yum.repos.d/mysql-community.repo
    mode: 0644
  become: true

- name: Install mysql-cluster-community-server
  yum:
    name: mysql-cluster-community-server
    state: present
  become: true

- name: Install config
  template:
    src: my.cnf
    dest: /etc/my.cnf
  become: true

- name: Start and Enable Mysql
  service:
    name: mysql
    state: started
    enabled: true

#mysql_secure_installation
# run mysqld as mysql user
# Can't open the mysql.plugin table
# Please run mysql_upgrade to create it.


#- name: Initialize ndb
#  command: ndbd --config
#  become: true
