- name: Add Mysql Repo
  template:
    src: mysql-community.repo.j2
    dest: /etc/yum.repos.d/mysql-community.repo
    mode: 0644
  become: true

- name: install mysql-cluster-community-management-server
  yum:
    name: mysql-cluster-community-management-server
    state: present

- name: Install mysql-cluster-community-server
  yum:
    name: mysql-cluster-community-server
    state: present
  become: true

# Firewalld task to connect data nodes
- name: check if firewalld exists
  stat:
    path: /etc/sysconfig/firewalld
  register: firewall_rules

- name: "Add port {{ mysql_ndb_port }}"
  firewalld:
    port: "{{ mysql_ndb_port }}/tcp"
    zone: public
    permanent: true
    state: enabled
  when: "firewall_rules.stat.exists == true"

- name: "[Firewall] add port {{ mysql_ndb_port }}"
  iptables:
   chain: INPUT
   protocol: tcp
   jump: ACCEPT
   destination_port: "{{ mysql_ndb_port }}"
  when: "firewall_rules.stat.exists == false"

- name: Restart FirewallD
  systemd:
    name: firewalld
    state: restarted
  become: true
  when: "firewall_rules.stat.exists == true"
# END FIREWALL

- name: Copy config.ini to /var/lib/mysql-cluster/
  template:
    src: config.ini.j2
    dest: /var/lib/mysql-cluster/config.ini
    mode: 0755
  become: true

- name: Initialize ndb_mgmd
  command: ndb_mgmd -f /var/lib/mysql-cluster/config.ini --initial --config-dir=/var/lib/mysql-cluster/
  become: true
  ignore_errors: true

# ndb_mgmd -f /var/lib/mysql-cluster/config.ini --initial --config-dir=/var/lib/mysql-cluster/

#- name: Initialize ndb_mgmd
#  command: ndb_mgmd
#  become: true
