- name: Add Mysql Repo
  template:
    src: mysql-community.repo.j2
    dest: /etc/yum.repos.d/mysql-community.repo
    mode: 0644
  become: true

- name: Install dependancies
  yum:
    name: ['perl-IO-Compress', 'perl-Net-LibIDN', 'perl-IO-String', 'perl-DBI', 'perl-Net-Daemon', ]
    state: present
  become: true

- name: Update pip for python dependancies
  command: "pip install --upgrade pip"
  become: true

#- name: Install the Python MySQLB module dependancy
#  pip:
#    name: MySQL-python #==1.2.5
#  become: true

# This installs a list of packages and
# creates the mysql user
# https://dev.mysql.com/doc/refman/8.0/en/mysql-cluster-install-linux-rpm.html
- name: Install mysql-cluster-community-server
  yum:
    name: mysql-cluster-community-server
    state: present
  become: true

- name: Create mysql log file
  file:
    path: /var/log/mysqld.log
    owner: mysql
    group: mysql
    mode: 0644
  become: true

# Firewalld task to connect data nodes
- name: check if firewalld exists
  stat:
    path: /etc/sysconfig/firewalld
  register: firewall_rules

- name: "Add port {{ mysql_port }}"
  firewalld:
    port: "{{ mysql_port }}/tcp"
    zone: public
    permanent: true
    state: enabled
  when: "firewall_rules.stat.exists == true"

- name: "[Firewall] add port {{ mysql_port }}"
  iptables:
   chain: INPUT
   protocol: tcp
   jump: ACCEPT
   destination_port: "{{ mysql_port }}"
  when: "firewall_rules.stat.exists == false"

- name: Restart FirewallD
  systemd:
    name: firewalld
    state: restarted
  become: true
  when: "firewall_rules.stat.exists == true"
# END FIREWALL

- name: Set permissions for mysql data dir
  file:
    path: /var/lib/mysql/
    owner: mysql
    group: mysql
    recurse: yes
    mode: 0755

- name: Install config
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
  become: true

# Setting up Mysql secure connection
- import_tasks: "secure.yml"
