- name: Add Mysql Repo
  template:
    src: mysql-community.repo.j2
    dest: /etc/yum.repos.d/mysql-community.repo
    mode: 0644
  become: true

# This installs a list of packages and
# creates the mysql user
# https://dev.mysql.com/doc/refman/8.0/en/mysql-cluster-install-linux-rpm.html
- name: Install mysql-cluster-community-server
  yum:
    name: mysql-cluster-community-server
    state: present
  become: true

- name: Create mysql log file
  file:
    path: /var/log/mysqld.log
    owner: mysql
    group: mysql
    mode: 0644
  become: true

- name: Install config
  template:
    src: sqlnode.cnf.j2
    dest: /etc/my.cnf
  become: true
 
