- name: Add Mysql Repo
  template:
    src: mysql-community.repo.j2
    dest: /etc/yum.repos.d/mysql-community.repo
    mode: 0644
  become: true

- name: Install mysql-cluster-community-server
  yum:
    name: mysql-cluster-community-server
    state: present
  become: true

- name: Install config
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
  become: true
 
