- name: Add Mysql Repo
  template:
    src: mysql-community-8.repo
    dest: /etc/yum.repos.d/mysql-community-8.repo
    mode: 0644
  become: true

- name: install mysql-cluster-community-management-server
  yum:
    name: mysql-cluster-community-management-server
    state: present

#- name: install  mysql-cluster-community-ndbclien
#  yum:
#    name: mysql-cluster-community-ndbclient
#    state: present

# https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm

# shell> rpm -Uhv mysql-cluster-commercial-management-server-8.0.18-1.el7.x86_64.rpm

# Firewalld task to connect data nodes
- name: check if firewalld exists
  stat:
    path: /etc/sysconfig/firewalld
  register: firewall_rules

- name: add port 1186
  firewalld:
    port: 1186/tcp
    zone: public
    permanent: true
    state: enabled
  when: "firewall_rules.stat.exists == true"

- name: "[Firewall] add port 1186"
  iptables:
   chain: INPUT
   protocol: tcp
   jump: ACCEPT
   destination_port: 1186
  when: "firewall_rules.stat.exists == false"

- name: Restart FirewallD
  systemd:
    name: firewalld
    state: restarted
  become: true
  when: "firewall_rules.stat.exists == true"

- name: Copy config
  template:
    src: config.ini
    dest: /var/lib/mysql-cluster/config.ini
    mode: 0755
  become: true
  
- name: Initialize ndb_mgmd
  command: ndb_mgmd -f /var/lib/mysql-cluster/config.ini --initial --config-dir=/var/lib/mysql-cluster/
  args:
    creates: /var/lib/mysql-cluster/ndb_1_cluster.log
  become: true
