- name: Add Mysql Repo
  template:
    src: mysql-community.repo.j2
    dest: /etc/yum.repos.d/mysql-community.repo
    mode: 0644
  become: true

- name: install mysql-cluster-community-data-node
  yum:
    name: mysql-cluster-community-data-node
    state: present
  become: true

- name: Recursively change ownership of /usr/local/mysql/data/
  file:
    path: /usr/local/mysql/data
    state: directory
    recurse: yes
    owner: mysql
    group: mysql
  become: true

- name: Install config
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
  become: true

- name: Initialize ndb
  command: ndbd --initial
  become: true
  ignore_errors: true
