- name: Download binaries
  command: wget --continue -P /var/tmp "{{ mysql_dl_url }}"

- name: Extract binaries
  command: tar -C /var/tmp -xzf /var/tmp/"{{ mysql_dl_tar }}" creates=/var/tmp/{{ mysql_dl_tar_dir }}/

- name: Install nbd binaries
  command: install ndb_mgmd ndb_mgm /usr/local/bin/
  args:
    chdir: "/var/tmp/{{ mysql_bin_dir }}"
    creates: /usr/local/bin/ndb_mgmd
  become: true

- name: Install init file
  copy:
    src: ndb_mgmd.init
    dest: /etc/init.d/ndb_mgmd
  become: true

- name: Activate init file
  service:
    name: ndb_mgmd
    enabled: yes
  become: true

- name: Create data dir
  file:
    path: /var/lib/mysql-cluster
    state: directory
    mode: 0755
  become: true

- name: Copy config
  template:
    src: config.ini
    dest: /var/lib/mysql-cluster/config.ini
    mode: 0755
  become: true

# Firewalld task to connect data nodes
- name: check if firewalld exists
  stat:
    path: /etc/sysconfig/firewalld
  register: firewall_rules

- name: add port 1186
  firewalld:
    port: 1186/tcp
    zone: public
    permanent: true
    state: enabled
  when: "firewall_rules.stat.exists == true"

- name: "[Firewall] add port 1186"
  iptables:
   chain: INPUT
   protocol: tcp
   jump: ACCEPT
   destination_port: 1186
  when: "firewall_rules.stat.exists == false"

- name: Restart FirewallD
  systemd:
    name: firewalld
    state: restarted
  become: true
  when: "firewall_rules.stat.exists == true"

- name: Initialize ndb_mgmd
  command: ndb_mgmd -f /var/lib/mysql-cluster/config.ini --initial --config-dir=/var/lib/mysql-cluster/
  args:
    creates: /var/lib/mysql-cluster/ndb_1_cluster.log
  become: true
